// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

type Priority int32

const (
	PriorityTSDEFAULT Priority = 0
	PriorityLOW       Priority = 1
	PriorityMEDIUM    Priority = 2
	PriorityHIGH      Priority = 3
)

var EnumNamesPriority = map[Priority]string{
	PriorityTSDEFAULT: "TSDEFAULT",
	PriorityLOW:       "LOW",
	PriorityMEDIUM:    "MEDIUM",
	PriorityHIGH:      "HIGH",
}
