// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

type StorageClass int32

const (
	StorageClassREPLICATED StorageClass = 0
	StorageClassRS_6_3     StorageClass = 1
	StorageClassRS_8_3     StorageClass = 2
	StorageClassRS_10_3    StorageClass = 3
	StorageClassRS_12_5    StorageClass = 4
)

var EnumNamesStorageClass = map[StorageClass]string{
	StorageClassREPLICATED: "REPLICATED",
	StorageClassRS_6_3:     "RS_6_3",
	StorageClassRS_8_3:     "RS_8_3",
	StorageClassRS_10_3:    "RS_10_3",
	StorageClassRS_12_5:    "RS_12_5",
}
