// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

type StorageHint int32

const (
	StorageHintDEFAULT StorageHint = 0
	StorageHintHOT     StorageHint = 1
	StorageHintWARM    StorageHint = 2
	StorageHintCOLD    StorageHint = 3
)

var EnumNamesStorageHint = map[StorageHint]string{
	StorageHintDEFAULT: "DEFAULT",
	StorageHintHOT:     "HOT",
	StorageHintWARM:    "WARM",
	StorageHintCOLD:    "COLD",
}
