; Copyright (c) 2015 Western Digital Corporation or its affiliates.  All rights reserved.
; SPDX-License-Identifier: MIT

(defproject jepsen.raftkv "0.1.0-SNAPSHOT"
  :description "jepsen test for raftkv"
  :url "https://github.com/westerndigitalcorporation/blb/tree/master/internal/raftkv/jepsen/"
  :license {:name "MIT"
            :url "https://opensource.org/licenses/MIT"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [jepsen "0.0.6"]
                 [clj-http "1.0.1"]]
  ; It might take a lot of memory to analyzing operation history generated by jepsen test.
  ::jvm-opts ["-Xmx4g"])
